# Generated by Django 6.0.7 on 2026-07-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_amount_paid_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL_MONEY', 'Airtel Money')], default='MPESA', max_length=30),
        ),
    ]
